# Generated by Django 5.2.4 on 2025-11-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=200)),
                ('customerEmail', models.EmailField(max_length=254, unique=True)),
                ('customerPhone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transactionDate', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=100)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
    ]
