# Generated by Django 5.2.4 on 2025-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
